### Basic Indexing and slicing

In [2]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5:8]

array([5, 6, 7])

In [4]:
#storing the sliced array

arr_sliced = arr[5:8]

In [5]:
arr_sliced

array([5, 6, 7])

In [8]:
arr_sliced[1] = 12345

In [9]:
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [17]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d.shape
old_values = arr3d[0].copy()

In [21]:
arr3d[0] = 42
arr3d
arr3d[0] = old_values

In [26]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [27]:
x[0]

array([7, 8, 9])

In [37]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
arr2d[:2,1:]
lower_dim_slice = arr2d[1, :2]
lower_dim_slice

array([4, 5])

### Fancy Indexing


In [41]:
#declaring a 8x4 matrix
arr = np.zeros((8,4))
arr
for i in range(8):
    arr[i] = i

In [42]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [43]:
arr[[0,1,2]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [44]:
arr[[-2,-5,-7]]

array([[6., 6., 6., 6.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [46]:
#selecting different elements out of an array
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [47]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [54]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [55]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [56]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

### Transposing Arrays and Swapping Axes

In [58]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
#dot product of array
np.dot(arr.T,arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [59]:
#also a dot product    
#The @ operator is also known as infix operatior

arr.T@arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [70]:
print(arr) 
print(arr.swapaxes(0,1))    #also a transpose method
print(arr.T)                #Transpose with T

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]
[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]
[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]


### Pseudorandom Number Generation

In [77]:
arr = np.random.standard_normal(size=(4,4))

In [80]:
arr.T@arr

array([[ 7.10475241,  6.53380056,  1.41355519,  2.34210872],
       [ 6.53380056, 12.29518899,  1.78174875,  3.22000917],
       [ 1.41355519,  1.78174875,  2.68031655,  0.3489436 ],
       [ 2.34210872,  3.22000917,  0.3489436 ,  1.32327894]])

In [113]:
#comparing python builtin vs 
#np.random
N = 1_000_000
from random import normalvariate
%timeit samples= [normalvariate(0,1) for i in range(N)]

744 ms ± 42.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [121]:
#now using the numpy function

samples2 = [np.random.standard_normal() for _ in range(N)]

In [1]:
samples2d

NameError: name 'samples2d' is not defined